export const TYPES = {
    SET_DELIVERY_ITEMS: 'SET_DELIVERY_ITEMS',
    SELECT_DELIVERY: 'SELECT_DELIVERY',
    START_DELIVERY: 'START_DELIVERY',
    REJECT_DELIVERY: 'REJECT_DELIVERY',
    UPDATE_DELIVERY_STATUS: 'UPDATE_DELIVERY_STATUS',
    SET_REJECTION_DATA: 'SET_REJECTION_DATA',
    CLEAR_REJECTION_DATA: 'CLEAR_REJECTION_DATA',

    SET_ZOOM_LEVEL: 'SET_ZOOM_LEVEL',
    UPDATE_REGION: 'UPDATE_REGION',
    SET_SEARCH_QUERY: 'SET_SEARCH_QUERY',
    SET_SELECTED_MARKER: 'SET_SELECTED_MARKER',
};
