export const DELIVERY_ITEMS = [
    {
        id: '1',
        status: 'In Progress',
        location: 'New York, NY',
        store: 'Walmart',
        nextRoute: 'Philadelphia, PA',
        date: 'Feb 12, 2024 - Feb 12, 2024',
        time: '2:30 PM - 4:00 PM',
        routes: '3',
    },
    {
        id: '2',
        status: 'New',
        location: 'Boston, MA',
        store: 'Target',
        nextRoute: 'Providence, RI',
        date: 'Feb 11, 2024 - Feb 12, 2024',
        time: '3:45 PM - 4:00 PM',
        routes: '2',
    },
    {
        id: '3',
        status: 'Completed',
        location: 'Chicago, IL',
        store: 'Best Buy',
        nextRoute: 'Milwaukee, WI',
        date: 'Feb 10, 2024 - Feb 12, 2024',
        time: '1:15 PM - 4:00 PM',
        routes: '4',
    },
    {
        id: '4',
        status: 'In Progress',
        location: 'Miami, FL',
        store: 'Costco',
        nextRoute: 'Orlando, FL',
        date: 'Feb 9, 2024 - Feb 12, 2024',
        time: '3:00 PM - 4:00 PM',
        routes: '1',
    },
    {
        id: '5',
        status: 'New',
        location: 'Los Angeles, CA',
        store: "Sam's Club",
        nextRoute: 'San Diego, CA',
        date: 'Feb 8, 2024 - Feb 12, 2024',
        time: '11:00 AM - 2:00 PM',
        routes: '5',
    },
    {
        id: '6',
        status: 'Cancelled',
        location: 'Houston, TX',
        store: 'Kroger',
        nextRoute: 'Austin, TX',
        date: 'Feb 7, 2024 - Feb 12, 2024',
        time: '9:00 AM - 10:00 AM',
        routes: '2',
    },
    {
        id: '7',
        status: 'In Progress',
        location: 'Phoenix, AZ',
        store: 'Albertsons',
        nextRoute: 'Tucson, AZ',
        date: 'Feb 6, 2024 - Feb 12, 2024',
        time: '4:00 PM - 5:30 PM',
        routes: '3',
    },
    {
        id: '8',
        status: 'Completed',
        location: 'San Francisco, CA',
        store: "Trader Joe's",
        nextRoute: 'Sacramento, CA',
        date: 'Feb 5, 2024 - Feb 12, 2024',
        time: '12:00 PM - 1:00 PM',
        routes: '1',
    },
    {
        id: '9',
        status: 'In Progress',
        location: 'Denver, CO',
        store: 'Whole Foods',
        nextRoute: 'Colorado Springs, CO',
        date: 'Feb 4, 2024 - Feb 12, 2024',
        time: '6:00 PM - 7:00 PM',
        routes: '4',
    },
    {
        id: '10',
        status: 'Completed',
        location: 'Seattle, WA',
        store: 'Safeway',
        nextRoute: 'Portland, OR',
        date: 'Feb 3, 2024 - Feb 12, 2024',
        time: '10:00 AM - 11:30 AM',
        routes: '2',
    },
    {
        id: '11',
        status: 'Completed',
        location: 'Dallas, TX',
        store: 'H-E-B',
        nextRoute: 'Oklahoma City, OK',
        date: 'Feb 2, 2024 - Feb 12, 2024',
        time: '5:00 PM - 6:00 PM',
        routes: '3',
    },
    {
        id: '12',
        status: 'In Progress',
        location: 'Atlanta, GA',
        store: 'Publix',
        nextRoute: 'Charlotte, NC',
        date: 'Feb 1, 2024 - Feb 12, 2024',
        time: '7:00 AM - 8:30 AM',
        routes: '1',
    },
    {
        id: '13',
        status: 'Cancelled',
        location: 'Las Vegas, NV',
        store: 'WinCo Foods',
        nextRoute: 'Reno, NV',
        date: 'Jan 31, 2024 - Feb 12, 2024',
        time: '2:00 PM - 3:00 PM',
        routes: '4',
    },
    {
        id: '14',
        status: 'New',
        location: 'Portland, OR',
        store: 'Fred Meyer',
        nextRoute: 'Eugene, OR',
        date: 'Jan 30, 2024 - Feb 12, 2024',
        time: '9:30 AM - 10:45 AM',
        routes: '5',
    },
];
