export const DELIVERY_ITEMS = [
    {
        id: '1',
        status: 'In Progress',
        location: 'San Francisco, CA',
        store: 'Walmart',
        nextRoute: [
            {
                place: 'Market Street',
                expectedTimeArrival: 'Feb 12, 2024, 2:45 PM',
                expectedTimeDeparture: 'Feb 12, 2024, 3:00 PM',
                serviceType: 'Pick up',
            },
            {
                place: '1st Street',
                expectedTimeArrival: 'Feb 12, 2024, 3:15 PM',
                expectedTimeDeparture: 'Feb 12, 2024, 3:30 PM',
                serviceType: 'Drop off',
            },
            {
                place: 'Mission Street',
                expectedTimeArrival: 'Feb 12, 2024, 3:45 PM',
                expectedTimeDeparture: 'Feb 12, 2024, 4:00 PM',
                serviceType: 'Drop off',
            },
            {
                place: 'Van Ness Avenue',
                expectedTimeArrival: 'Feb 12, 2024, 4:15 PM',
                expectedTimeDeparture: 'Feb 12, 2024, 4:30 PM',
                serviceType: 'Pick up',
            },
            {
                place: 'Lombard Street',
                expectedTimeArrival: 'Feb 12, 2024, 4:45 PM',
                expectedTimeDeparture: 'Feb 12, 2024, 5:00 PM',
                serviceType: 'Drop off',
            },
        ],
        date: 'Feb 12, 2024 - Feb 12, 2024',
        time: '2:30 PM - 4:00 PM',
        routes: '3',
        bodyNumber: 'TRK-1023',
        driver: 'John Doe',
        plateNumber: '7ABC123',
        routeCoordinates: [
            { latitude: 37.7833, longitude: -122.4167, name: 'Market Street' },
            { latitude: 37.7846, longitude: -122.4017, name: '1st Street' },
            { latitude: 37.7900, longitude: -122.4200, name: 'Mission Street' },
            { latitude: 37.7752, longitude: -122.4194, name: 'Van Ness Avenue' },
            { latitude: 37.8021, longitude: -122.4187, name: 'Lombard Street' },
        ],
    },
    {
        id: '2',
        status: 'New',
        location: 'San Francisco, CA',
        store: 'Target',
        nextRoute: [
            {
                place: 'San Francisco, CA - Pier 39',
                expectedTimeArrival: 'Feb 11, 2024, 3:50 PM',
                expectedTimeDeparture: 'Feb 11, 2024, 3:55 PM',
                serviceType: 'Pick up',
            },
            {
                place: 'San Francisco, CA - Fisherman’s Wharf',
                expectedTimeArrival: 'Feb 11, 2024, 3:55 PM',
                expectedTimeDeparture: 'Feb 11, 2024, 4:00 PM',
                serviceType: 'Drop off',
            },
        ],
        date: 'Feb 11, 2024 - Feb 12, 2024',
        time: '3:45 PM - 4:00 PM',
        routes: '2',
        bodyNumber: 'TRK-2048',
        driver: 'Jane Smith',
        plateNumber: '6XYZ789',
        routeCoordinates: [
            { latitude: 37.8080, longitude: -122.4098, name: 'Pier 39' },
            { latitude: 37.8051, longitude: -122.4052, name: 'Fisherman’s Wharf' },
        ],
    },
    {
        id: '3',
        status: 'New',
        location: 'Los Angeles, CA',
        store: 'Best Buy',
        nextRoute: [
            {
                place: 'Los Angeles, CA - Sunset Blvd',
                expectedTimeArrival: 'Feb 10, 2024, 1:00 PM',
                expectedTimeDeparture: 'Feb 10, 2024, 1:15 PM',
                serviceType: 'Pick up',
            },
            {
                place: 'Los Angeles, CA - Hollywood Blvd',
                expectedTimeArrival: 'Feb 10, 2024, 1:30 PM',
                expectedTimeDeparture: 'Feb 10, 2024, 1:45 PM',
                serviceType: 'Drop off',
            },
        ],
        date: 'Feb 10, 2024',
        time: '12:45 PM - 1:45 PM',
        routes: '2',
        bodyNumber: 'TRK-3057',
        driver: 'Mark Johnson',
        plateNumber: '5LMN456',
        routeCoordinates: [
            { latitude: 34.0983, longitude: -118.3295, name: 'Sunset Blvd' },
            { latitude: 34.1010, longitude: -118.3297, name: 'Hollywood Blvd' },
        ],
    },
    {
        id: '4',
        status: 'Delayed',
        location: 'New York, NY',
        store: 'Costco',
        nextRoute: [
            {
                place: 'New York, NY - 5th Avenue',
                expectedTimeArrival: 'Feb 13, 2024, 10:30 AM',
                expectedTimeDeparture: 'Feb 13, 2024, 10:45 AM',
                serviceType: 'Pick up',
            },
            {
                place: 'New York, NY - Times Square',
                expectedTimeArrival: 'Feb 13, 2024, 11:00 AM',
                expectedTimeDeparture: 'Feb 13, 2024, 11:15 AM',
                serviceType: 'Drop off',
            },
        ],
        date: 'Feb 13, 2024',
        time: '10:15 AM - 11:15 AM',
        routes: '2',
        bodyNumber: 'TRK-4068',
        driver: 'Emily Davis',
        plateNumber: '8QRS789',
        routeCoordinates: [
            { latitude: 40.7570, longitude: -73.9855, name: '5th Avenue' },
            { latitude: 40.7580, longitude: -73.9855, name: 'Times Square' },
        ],
    },
    {
        id: '5',
        status: 'In Progress',
        location: 'Chicago, IL',
        store: 'Home Depot',
        nextRoute: [
            {
                place: 'Chicago, IL - Michigan Avenue',
                expectedTimeArrival: 'Feb 14, 2024, 2:00 PM',
                expectedTimeDeparture: 'Feb 14, 2024, 2:15 PM',
                serviceType: 'Pick up',
            },
            {
                place: 'Chicago, IL - Navy Pier',
                expectedTimeArrival: 'Feb 14, 2024, 2:30 PM',
                expectedTimeDeparture: 'Feb 14, 2024, 2:45 PM',
                serviceType: 'Drop off',
            },
        ],
        date: 'Feb 14, 2024',
        time: '1:45 PM - 2:45 PM',
        routes: '2',
        bodyNumber: 'TRK-5079',
        driver: 'Michael Brown',
        plateNumber: '9TUV123',
        routeCoordinates: [
            { latitude: 41.8917, longitude: -87.6067, name: 'Michigan Avenue' },
            { latitude: 41.8916, longitude: -87.6094, name: 'Navy Pier' },
        ],
    },
];
