export const SAMPLE_LOGS = [
    {
        id: 1,
        route: 'Walmart',
        status: 'Arrived at location',
        location: 'Los Angeles, CA',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:30:00Z',
    },
    {
        id: 2,
        route: 'Target',
        status: 'Loading cargo',
        location: 'San Francisco, CA',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:25:00Z',
    },
    {
        id: 3,
        route: 'Costco',
        status: 'Loaded cargo',
        location: 'New York, NY',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:20:00Z',
    },
    {
        id: 4,
        route: 'Amazon Warehouse',
        status: 'Unloading cargo',
        location: 'Chicago, IL',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:15:00Z',
    },
    {
        id: 5,
        route: 'Best Buy',
        status: 'Unloaded cargo',
        location: 'Houston, TX',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:10:00Z',
    },
    {
        id: 6,
        route: 'Home Depot',
        status: 'Unloaded cargo',
        location: 'Seattle, WA',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:05:00Z',
    },
    {
        id: 7,
        route: "Lowe's",
        status: 'Unloading cargo',
        location: 'Denver, CO',
        minutesAgo: 5,
        timestamp: '2024-02-12T10:00:00Z',
    },
    {
        id: 8,
        route: 'Walgreens',
        status: 'Loaded cargo',
        location: 'Miami, FL',
        minutesAgo: 5,
        timestamp: '2024-02-12T09:55:00Z',
    },
    {
        id: 9,
        route: 'CVS Pharmacy',
        status: 'Loading cargo',
        location: 'Boston, MA',
        minutesAgo: 40,
        timestamp: '2024-02-12T09:50:00Z',
    },
    {
        id: 10,
        route: "Sam's Club",
        status: 'Arrived at location',
        location: 'Atlanta, GA',
        minutesAgo: 55,
        timestamp: '2024-02-12T09:35:00Z',
    },
    {
        id: 11,
        route: 'Jollibee',
        status: 'Delivered',
        location: 'Austin, TX',
        minutesAgo: 55,
        timestamp: '2024-02-12T09:30:00Z',
    },
];
